version: '3.8'
services:
  web:
    image: php:8.2-apache
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - DB_HOST=localhost
      - DB_NAME=name
      - DB_USER=root
      - DB_PASSWORD=""
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
